### ISSUE TITLE
converting inline %prec in bison grammars leaves extra symbols

### ISSUE THREAD

**Issue by SKalt** [kaby76/Domemtech.Trash#11]
Using the latest version of trash (8.5),
```yacc
// bison
SelectStmt: select_no_parens			%prec UMINUS
			| select_with_parens		%prec UMINUS
		;
```

becomes 

```antlr
selectStmt  : select_no_parens UMINUS
  | select_with_parens UMINUS
  ;
```
The desired outcome is 

```antlr
selectStmt  : select_no_parens
  | select_with_parens
  ;
```

**Comment by kaby76** [comment]
I have a fix to filter out the symbols after `%prec`, but I don't currently do anything to adjust the rules for precedence. For the moment, this will have to suffice. I.e., instead of `//symbol`, the XPath expression to grab `symbols` on the RHS of a rule is now `//symbol[not(preceding-sibling::PERCENT_PREC)]`.

**Comment by SKalt** [comment]
> filter out the symbols after %prec

The filtering is working for me.

> I don't currently do anything to adjust the rules for precedence.

I've been intending to maintain precedence semi-manually by applying a series of patches to the auto-converted grammar.
